#!/usr/bin/env python3
"""
Universal Application Theme Synchronizer for Quickshell
Synchronizes active theme palette to:
1. GTK4 / Libadwaita (Nautilus, Loupe, GNOME Music, GNOME Camera, GNOME Calculator)
2. Ghostty terminal emulator
3. VSCodium
4. Zen Browser
"""

import sys
import os
import json
import glob
import time
import subprocess
from pathlib import Path

HOME = Path.home()
CONFIG_DIR = HOME / ".config" / "quickshell"
PALETTES_FILE = CONFIG_DIR / "theme" / "palettes.json"

def load_palettes():
    if not PALETTES_FILE.exists():
        print(f"Error: Palettes file {PALETTES_FILE} does not exist.")
        sys.exit(1)
    with open(PALETTES_FILE, "r") as f:
        return json.load(f)

def sync_gtk(palette):
    """
    Sync GTK4 / Libadwaita and GTK3 themes.
    Applies to Nautilus, Loupe, GNOME Music, Camera, Calculator, etc.
    """
    gtk4_dir = HOME / ".config" / "gtk-4.0"
    gtk3_dir = HOME / ".config" / "gtk-3.0"
    gtk4_dir.mkdir(parents=True, exist_ok=True)
    gtk3_dir.mkdir(parents=True, exist_ok=True)

    p = palette

    # 1. Generate theme.css with full Libadwaita color definitions, media query overrides, and element rules
    theme_css = f"""/* Generated by Quickshell Theme Sync - Palette: {p['name']} */

/* Dark mode media query override for Libadwaita */
@media (prefers-color-scheme: dark) {{
  @define-color accent_color {p['accent']};
  @define-color accent_bg_color {p['accent']};
  @define-color accent_fg_color {p['bgBase']};

  @define-color destructive_color {p['red']};
  @define-color destructive_bg_color {p['red']};
  @define-color destructive_fg_color #ffffff;

  @define-color success_color {p['green']};
  @define-color success_bg_color {p['green']};
  @define-color success_fg_color #ffffff;

  @define-color warning_color {p['yellow']};
  @define-color warning_bg_color {p['yellow']};
  @define-color warning_fg_color #ffffff;

  @define-color error_color {p['red']};
  @define-color error_bg_color {p['red']};
  @define-color error_fg_color #ffffff;

  @define-color window_bg_color {p['bgBase']};
  @define-color window_fg_color {p['textPrimary']};

  @define-color view_bg_color {p['bgSurface']};
  @define-color view_fg_color {p['textPrimary']};

  @define-color headerbar_bg_color {p['bgBase']};
  @define-color headerbar_fg_color {p['textPrimary']};
  @define-color headerbar_border_color {p['borderNormal']};
  @define-color headerbar_backdrop_color {p['bgBase']};

  @define-color card_bg_color {p['bgSurface']};
  @define-color card_fg_color {p['textPrimary']};
  @define-color card_border_color {p['borderDim']};

  @define-color popover_bg_color {p['bgSurface']};
  @define-color popover_fg_color {p['textPrimary']};
  @define-color popover_border_color {p['borderNormal']};

  @define-color dialog_bg_color {p['bgBase']};
  @define-color dialog_fg_color {p['textPrimary']};

  @define-color sidebar_bg_color {p['bgBase']};
  @define-color sidebar_fg_color {p['textPrimary']};
  @define-color sidebar_backdrop_color {p['bgBase']};
  @define-color sidebar_border_color {p['borderDim']};

  @define-color secondary_sidebar_bg_color {p['bgSurface']};
  @define-color secondary_sidebar_fg_color {p['textPrimary']};
  @define-color secondary_sidebar_backdrop_color {p['bgSurface']};

  :root {{
    --accent-bg-color: {p['accent']};
    --accent-fg-color: {p['bgBase']};
    --accent-color: {p['accent']};
    --window-bg-color: {p['bgBase']};
    --window-fg-color: {p['textPrimary']};
    --view-bg-color: {p['bgSurface']};
    --view-fg-color: {p['textPrimary']};
    --headerbar-bg-color: {p['bgBase']};
    --headerbar-fg-color: {p['textPrimary']};
    --headerbar-border-color: {p['borderNormal']};
    --sidebar-bg-color: {p['bgBase']};
    --sidebar-fg-color: {p['textPrimary']};
    --sidebar-border-color: {p['borderDim']};
    --card-bg-color: {p['bgSurface']};
    --card-fg-color: {p['textPrimary']};
    --dialog-bg-color: {p['bgBase']};
    --dialog-fg-color: {p['textPrimary']};
    --popover-bg-color: {p['bgSurface']};
    --popover-fg-color: {p['textPrimary']};
    --popover-border-color: {p['borderNormal']};
  }}
}}

/* Global definitions */
@define-color accent_color {p['accent']};
@define-color accent_bg_color {p['accent']};
@define-color accent_fg_color {p['bgBase']};
@define-color window_bg_color {p['bgBase']};
@define-color window_fg_color {p['textPrimary']};
@define-color view_bg_color {p['bgSurface']};
@define-color view_fg_color {p['textPrimary']};
@define-color headerbar_bg_color {p['bgBase']};
@define-color headerbar_fg_color {p['textPrimary']};
@define-color headerbar_border_color {p['borderNormal']};
@define-color card_bg_color {p['bgSurface']};
@define-color card_fg_color {p['textPrimary']};
@define-color sidebar_bg_color {p['bgBase']};
@define-color sidebar_fg_color {p['textPrimary']};
@define-color sidebar_border_color {p['borderDim']};
@define-color popover_bg_color {p['bgSurface']};
@define-color popover_fg_color {p['textPrimary']};
@define-color popover_border_color {p['borderNormal']};

:root {{
  --accent-bg-color: {p['accent']};
  --accent-fg-color: {p['bgBase']};
  --accent-color: {p['accent']};
  --window-bg-color: {p['bgBase']};
  --window-fg-color: {p['textPrimary']};
  --view-bg-color: {p['bgSurface']};
  --view-fg-color: {p['textPrimary']};
  --headerbar-bg-color: {p['bgBase']};
  --headerbar-fg-color: {p['textPrimary']};
  --headerbar-border-color: {p['borderNormal']};
  --sidebar-bg-color: {p['bgBase']};
  --sidebar-fg-color: {p['textPrimary']};
  --sidebar-border-color: {p['borderDim']};
  --card-bg-color: {p['bgSurface']};
  --card-fg-color: {p['textPrimary']};
  --popover-bg-color: {p['bgSurface']};
  --popover-fg-color: {p['textPrimary']};
  --popover-border-color: {p['borderNormal']};
}}

/* Base Window styling (excluding popups / popovers) */
window:not(popover):not(.popup),
window.background:not(popover):not(.popup),
.background:not(popover):not(.popup) {{
  background-color: {p['bgBase']};
  color: {p['textPrimary']};
}}

/* Headerbar global styling */
headerbar,
headerbar.flat {{
  background-color: {p['bgBase']};
  color: {p['textPrimary']};
  border: none;
  box-shadow: none;
}}

/* ====================================================================
   Nautilus & Libadwaita Two-Column Split Architecture
   ==================================================================== */

/* Left column: Sidebar, its headerbar, and listbox share bgBase */
overlay-split-view > .sidebar-pane,
.sidebar-pane,
.sidebar-pane headerbar,
.sidebar-pane toolbarview,
.sidebar-pane listbox,
.sidebar-pane scrolledwindow,
.navigation-sidebar,
placessidebar,
placesview {{
  background-color: {p['bgBase']};
  color: {p['textPrimary']};
  border: none;
  box-shadow: none;
}}

/* Remove default Libadwaita inner shadow from sidebar pane */
overlay-split-view > .sidebar-pane:dir(ltr),
overlay-split-view > .sidebar-pane:dir(rtl),
.sidebar-pane:dir(ltr),
.sidebar-pane:dir(rtl) {{
  box-shadow: none;
}}

/* Single clean 1px vertical divider between Sidebar and Content */
overlay-split-view > border {{
  background-color: {p['borderDim']};
  min-width: 1px;
  min-height: 1px;
  border: none;
  box-shadow: none;
}}

overlay-split-view > shadow {{
  background-image: none;
  background: none;
  box-shadow: none;
}}

.sidebar-pane {{
  border-right: 1px solid {p['borderDim']};
}}

/* Sidebar row styling */
.sidebar-pane row,
.sidebar-pane listbox > row,
.navigation-sidebar listview > row,
placessidebar row {{
  background-color: transparent;
  color: {p['textPrimary']};
  border-radius: 6px;
  margin: 1px 4px;
}}

.sidebar-pane row:hover,
.sidebar-pane listbox > row:hover,
.navigation-sidebar listview > row:hover,
placessidebar row:hover {{
  background-color: {p['bgSurfaceHover']};
  color: {p['textPrimary']};
}}

.sidebar-pane row:selected,
.sidebar-pane listbox > row:selected,
.navigation-sidebar listview > row:selected,
placessidebar row:selected {{
  background-color: {p['bgSurfaceActive']};
  color: {p['accent']};
}}

.sidebar-pane row:selected label,
.sidebar-pane row:selected image,
.navigation-sidebar row:selected label {{
  color: {p['accent']};
}}

.sidebar-pane separator,
placessidebar separator {{
  background-color: {p['borderDim']};
  min-height: 1px;
  margin: 6px 12px;
}}

/* Right column: Content view, top location bar, and folder grid/list share unified bgSurface */
overlay-split-view > .content-pane,
.content-pane,
.content-pane toolbarview,
.content-pane .top-bar,
.content-pane headerbar,
.content-pane toolbarview > .top-bar,
.content-pane toolbarview > .top-bar headerbar {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: none;
  border-bottom: none;
  box-shadow: none;
}}

.content-pane .nautilus-files-view scrolledwindow,
.content-pane > scrolledwindow,
.content-pane toolbarview > scrolledwindow,
.content-pane .nautilus-files-view,
.content-pane .nautilus-list-view,
.content-pane .nautilus-grid-view,
.content-pane gridview,
.content-pane listview,
.content-pane columnview,
scrolledwindow.view {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: none;
}}

/* Nautilus Path Bar pill container */
.nautilus-pathbar {{
  background-color: color-mix(in srgb, currentColor 8%, transparent);
  border-radius: 8px;
  border: 1px solid {p['borderDim']};
  min-height: 32px;
  padding: 0;
  margin: 0;
}}

.nautilus-pathbar scrolledwindow,
.nautilus-pathbar > scrolledwindow {{
  background: transparent;
  background-color: transparent;
  border: none;
  box-shadow: none;
}}

.nautilus-pathbar > menubutton,
.nautilus-pathbar menubutton {{
  margin: 0;
  padding: 0;
  background: transparent;
  border: none;
}}

/* Nautilus Path Bar buttons (e.g. [Home], [Trash], and the three-dot button) */
.nautilus-pathbar .nautilus-path-button,
.nautilus-pathbar menubutton > button {{
  margin: 2px 1px;
  padding: 0 6px;
  min-height: 26px;
  min-width: 24px;
  border-radius: 6px;
  background: transparent;
  background-color: transparent;
  border: none;
  box-shadow: none;
  color: {p['textPrimary']};
}}

.nautilus-pathbar .nautilus-path-button:hover,
.nautilus-pathbar menubutton > button:hover {{
  background-color: color-mix(in srgb, currentColor 10%, transparent);
  color: {p['accent']};
}}

.nautilus-pathbar .nautilus-path-button:active,
.nautilus-pathbar .nautilus-path-button.current-dir,
.nautilus-pathbar menubutton > button:active,
.nautilus-pathbar menubutton > button:checked {{
  background-color: color-mix(in srgb, currentColor 15%, transparent);
  color: {p['accent']};
}}

/* Nautilus Location Entry (Ctrl+L address bar) */
entry.location-entry,
.nautilus-location-entry,
#location_entry {{
  min-height: 32px;
  border-radius: 8px;
  background-color: color-mix(in srgb, currentColor 8%, transparent);
  color: {p['textPrimary']};
  border: 1px solid {p['borderDim']};
  padding: 0 8px;
}}

/* Selected items in folder view */
.content-pane gridview > child:selected,
.content-pane listview > row:selected,
.content-pane columnview row:selected {{
  background-color: {p['bgSurfaceActive']};
  color: {p['accent']};
  border-radius: 6px;
}}

.content-pane gridview > child:hover,
.content-pane listview > row:hover {{
  background-color: {p['bgSurfaceHover']};
  border-radius: 6px;
}}

/* Action buttons */
button.suggested-action,
button.accent {{
  background-color: {p['accent']};
  color: {p['bgBase']};
}}

card {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderDim']};
}}

/* ====================================================================
   Popovers, Menus & Context Menus
   ==================================================================== */

popover,
popover.background,
popover.menu,
popover:backdrop,
.solid-csd popover,
.solid-csd popover.menu,
window.solid-csd popover,
window.csd popover,
window popover {{
  background: transparent;
  background-color: transparent;
  background-image: none;
  box-shadow: none;
  border: none;
  border-width: 0;
  border-style: none;
  border-color: transparent;
  outline: none;
  outline-width: 0;
  padding: 0;
  margin: 0;
}}

popover > contents,
.solid-csd popover > contents,
popover.menu > contents,
.solid-csd popover.menu > contents {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderNormal']};
  border-radius: 10px;
  background-clip: padding-box;
  box-shadow: none;
}}

popover > arrow,
.solid-csd popover > arrow {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderNormal']};
  border-radius: 0;
  box-shadow: none;
}}

popover.menu > contents {{
  padding: 4px;
  border-radius: 10px;
}}

popover.menu > contents > stack > box,
popover.menu > contents > scrolledwindow > viewport > stack > box {{
  padding: 0;
  border-radius: 8px;
}}

popover.menu modelbutton {{
  min-height: 30px;
  min-width: 40px;
  padding: 0 10px;
  border-radius: 6px;
}}

popover.menu modelbutton:hover,
popover.menu modelbutton:selected {{
  background-color: {p['bgSurfaceHover']};
  color: {p['accent']};
}}

popover.menu separator {{
  background-color: {p['borderDim']};
  min-height: 1px;
  margin: 4px 6px;
}}

/* GTK3 Classic Menus */
menu,
.menu {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderNormal']};
  border-radius: 8px;
  padding: 4px;
  box-shadow: none;
}}

menuitem,
.menu menuitem {{
  color: {p['textPrimary']};
  border-radius: 4px;
  padding: 4px 8px;
}}

menuitem:hover,
.menu menuitem:hover {{
  background-color: {p['bgSurfaceHover']};
  color: {p['accent']};
}}

menu separator,
separator.menuitem {{
  background-color: {p['borderDim']};
  min-height: 1px;
  margin: 4px 6px;
}}
"""
    theme_file_4 = gtk4_dir / "theme.css"
    with open(theme_file_4, "w") as f:
        f.write(theme_css)

    # 2. Write theme_css directly into gtk.css and gtk-dark.css so inotify triggers on them
    for fname in ["gtk.css", "gtk-dark.css"]:
        fpath = gtk4_dir / fname
        if fpath.is_symlink():
            fpath.unlink()
        with open(fpath, "w") as f:
            f.write(theme_css)

    # 3. Also configure gtk-3.0 (pure GTK3 CSS without @media or :root)
    gtk3_css = f"""/* Generated by Quickshell Theme Sync - GTK3 Palette: {p['name']} */
@define-color accent_color {p['accent']};
@define-color accent_bg_color {p['accent']};
@define-color accent_fg_color {p['bgBase']};
@define-color window_bg_color {p['bgBase']};
@define-color window_fg_color {p['textPrimary']};
@define-color view_bg_color {p['bgSurface']};
@define-color view_fg_color {p['textPrimary']};
@define-color headerbar_bg_color {p['bgBase']};
@define-color headerbar_fg_color {p['textPrimary']};
@define-color headerbar_border_color {p['borderNormal']};
@define-color card_bg_color {p['bgSurface']};
@define-color card_fg_color {p['textPrimary']};
@define-color sidebar_bg_color {p['bgBase']};
@define-color sidebar_fg_color {p['textPrimary']};
@define-color sidebar_border_color {p['borderDim']};
@define-color popover_bg_color {p['bgSurface']};
@define-color popover_fg_color {p['textPrimary']};
@define-color popover_border_color {p['borderNormal']};

window:not(popover):not(.popup),
window.background:not(popover):not(.popup),
.background:not(popover):not(.popup) {{
  background-color: {p['bgBase']};
  color: {p['textPrimary']};
}}

headerbar,
headerbar.flat {{
  background-color: {p['bgBase']};
  color: {p['textPrimary']};
  border: none;
  box-shadow: none;
}}

menu,
.menu {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderNormal']};
  border-radius: 8px;
  padding: 4px;
}}

menuitem,
.menu menuitem {{
  color: {p['textPrimary']};
  border-radius: 4px;
  padding: 4px 8px;
}}

menuitem:hover,
.menu menuitem:hover {{
  background-color: {p['bgSurfaceHover']};
  color: {p['accent']};
}}

menu separator,
separator.menuitem {{
  background-color: {p['borderDim']};
  min-height: 1px;
  margin: 4px 6px;
}}
"""
    gtk3_theme = gtk3_dir / "gtk.css"
    with open(gtk3_theme, "w") as f:
        f.write(gtk3_css)

    # Trigger GTK style cache flush in all running GTK apps by toggling gtk-theme to force D-Bus broadcast
    try:
        subprocess.run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "Adwaita"], capture_output=True)
        subprocess.run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "adw-gtk3-dark"], capture_output=True)
    except Exception:
        pass

    # If Nautilus has an active window in Hyprland, seamlessly restart it
    try:
        clients_json = subprocess.run(["hyprctl", "clients", "-j"], capture_output=True, text=True)
        has_nautilus_window = False
        if clients_json.returncode == 0 and clients_json.stdout.strip():
            import json as _json
            clients = _json.loads(clients_json.stdout)
            has_nautilus_window = any(c.get("class") == "org.gnome.Nautilus" for c in clients)

        if has_nautilus_window:
            subprocess.run(["nautilus", "-q"], capture_output=True)
            subprocess.run(["pkill", "-x", "nautilus"], capture_output=True)
            time.sleep(0.3)
            subprocess.Popen(["nautilus", "--no-desktop"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        else:
            # If closed, just terminate background daemon so next launch starts fresh
            subprocess.run(["nautilus", "-q"], capture_output=True)
    except Exception:
        pass

    print(f"  ✓ GTK4 / Libadwaita & GTK3 synced: {p['name']}")

def sync_icons(palette):
    """
    Sync WhiteSur icon theme variants to match the active theme palette colors.
    Updates GSettings, GTK3/4 settings.ini, and xsettingsd.
    """
    p = palette
    theme_id = p.get("id", "")

    whitesur_map = {
        "nord": "WhiteSur-nord-dark",
        "osaka-jade": "WhiteSur-green-dark",
        "everforest": "WhiteSur-green-dark",
        "lupine": "WhiteSur-purple-dark",
        "tokyo-night": "WhiteSur-purple-dark",
        "catppuccin": "WhiteSur-purple-dark",
        "solitude": "WhiteSur-dark",
        "gruvbox": "WhiteSur-yellow-dark",
        "ristretto": "WhiteSur-orange-dark",
    }

    icon_theme = whitesur_map.get(theme_id, "WhiteSur-dark")

    # Verify if icon theme directory exists
    icon_dirs = [
        HOME / ".local" / "share" / "icons" / icon_theme,
        HOME / ".icons" / icon_theme,
        Path("/usr/share/icons") / icon_theme,
    ]
    if not any(d.exists() for d in icon_dirs):
        icon_theme = "WhiteSur-dark"

    # 1. Update GSettings (notifies all running GTK apps live via D-Bus)
    try:
        subprocess.run(["gsettings", "set", "org.gnome.desktop.interface", "icon-theme", icon_theme], capture_output=True)
    except Exception:
        pass

    # 2. Update GTK 3.0 & GTK 4.0 settings.ini
    for config_subdir in ["gtk-3.0", "gtk-4.0"]:
        settings_file = HOME / ".config" / config_subdir / "settings.ini"
        if settings_file.exists():
            try:
                lines = settings_file.read_text(encoding="utf-8").splitlines()
                new_lines = []
                replaced = False
                for line in lines:
                    if line.startswith("gtk-icon-theme-name="):
                        new_lines.append(f"gtk-icon-theme-name={icon_theme}")
                        replaced = True
                    else:
                        new_lines.append(line)
                if not replaced:
                    new_lines.append(f"gtk-icon-theme-name={icon_theme}")
                settings_file.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
            except Exception:
                pass

    # 3. Update xsettingsd if present
    xsettings_file = HOME / ".config" / "xsettingsd" / "xsettingsd.conf"
    if xsettings_file.exists():
        try:
            lines = xsettings_file.read_text(encoding="utf-8").splitlines()
            new_lines = []
            replaced = False
            for line in lines:
                if line.startswith("Net/IconThemeName"):
                    new_lines.append(f'Net/IconThemeName "{icon_theme}"')
                    replaced = True
                else:
                    new_lines.append(line)
            if not replaced:
                new_lines.append(f'Net/IconThemeName "{icon_theme}"')
            xsettings_file.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
            subprocess.run(["pkill", "-HUP", "-x", "xsettingsd"], capture_output=True)
        except Exception:
            pass

    print(f"  ✓ Icon theme synced: {icon_theme} ({p['name']})")

def sync_ghostty(palette):
    """
    Sync Ghostty terminal emulator.
    Writes theme.ghostty and links it only in config.ghostty to avoid cycle errors.
    """
    ghostty_dir = HOME / ".config" / "ghostty"
    ghostty_dir.mkdir(parents=True, exist_ok=True)
    theme_ghostty = ghostty_dir / "theme.ghostty"

    content = f"""# Ghostty Theme - Palette: {palette['name']}
# Generated by Quickshell Theme Sync - do not edit directly
background = {palette['bgBase']}
foreground = {palette['textPrimary']}
cursor-color = {palette['accent']}
cursor-text = {palette['bgBase']}
selection-background = {palette['bgSurfaceActive']}
selection-foreground = {palette['textPrimary']}

# 16-color ANSI Palette
palette = 0={palette['bgSurface']}
palette = 1={palette['red']}
palette = 2={palette['green']}
palette = 3={palette['yellow']}
palette = 4={palette['blue']}
palette = 5={palette['purple']}
palette = 6={palette['cyan']}
palette = 7={palette['textSecondary']}

palette = 8={palette['borderBright']}
palette = 9={palette['red']}
palette = 10={palette['green']}
palette = 11={palette['yellow']}
palette = 12={palette['accent']}
palette = 13={palette['magenta']}
palette = 14={palette['cyan']}
palette = 15={palette['textPrimary']}
"""
    with open(theme_ghostty, "w") as f:
        f.write(content)

    # Remove ~/.config/ghostty/config if present to prevent Ghostty cycle error (config loading config.ghostty)
    duplicate_cfg = ghostty_dir / "config"
    if duplicate_cfg.exists() and duplicate_cfg.is_file():
        try:
            duplicate_cfg.unlink()
        except Exception:
            pass

    # Ensure config.ghostty includes ?theme.ghostty
    config_ghostty = ghostty_dir / "config.ghostty"
    if not config_ghostty.exists():
        with open(config_ghostty, "w") as f:
            f.write("config-file = ?theme.ghostty\n")
    else:
        cfg_text = config_ghostty.read_text()
        if "theme.ghostty" not in cfg_text:
            with open(config_ghostty, "w") as f:
                f.write("config-file = ?theme.ghostty\n" + cfg_text)
        else:
            config_ghostty.touch()

    # Signal Ghostty to reload configuration live (SIGUSR2)
    try:
        subprocess.run(["pkill", "-SIGUSR2", "-x", "ghostty"], capture_output=True)
    except Exception:
        pass

    print(f"  ✓ Ghostty synced: {palette['name']}")

def sync_vscodium(palette):
    """
    Sync VSCodium workbench and editor colors.
    Updates workbench.colorCustomizations in settings.json.
    """
    settings_path = HOME / ".config" / "VSCodium" / "User" / "settings.json"
    if not settings_path.parent.exists():
        settings_path.parent.mkdir(parents=True, exist_ok=True)

    settings = {}
    if settings_path.exists():
        try:
            with open(settings_path, "r", encoding="utf-8") as f:
                settings = json.load(f)
        except Exception as e:
            print(f"  ! Warning: could not parse VSCodium settings.json: {e}")
            settings = {}

    p = palette
    customizations = {
        "activityBar.background": p["bgBase"],
        "activityBar.foreground": p["accent"],
        "activityBar.activeBorder": p["accent"],
        "activityBarBadge.background": p["accent"],
        "activityBarBadge.foreground": p["bgBase"],
        "editor.background": p["bgBase"],
        "editor.foreground": p["textPrimary"],
        "editorLineNumber.foreground": p["borderBright"],
        "editorLineNumber.activeForeground": p["accent"],
        "editorCursor.foreground": p["accent"],
        "editor.selectionBackground": p["bgSurfaceActive"],
        "editorGroupHeader.tabsBackground": p["bgSurface"],
        "tab.activeBackground": p["bgBase"],
        "tab.activeForeground": p["textPrimary"],
        "tab.activeBorderTop": p["accent"],
        "tab.inactiveBackground": p["bgSurface"],
        "tab.inactiveForeground": p["textMuted"],
        "sideBar.background": p["bgSurface"],
        "sideBar.foreground": p["textPrimary"],
        "sideBarTitle.foreground": p["textSecondary"],
        "sideBarSectionHeader.background": p["bgSurfaceHover"],
        "sideBarSectionHeader.foreground": p["accent"],
        "statusBar.background": p["bgSurface"],
        "statusBar.foreground": p["textSecondary"],
        "statusBarItem.remoteBackground": p["accent"],
        "titleBar.activeBackground": p["bgBase"],
        "titleBar.activeForeground": p["textPrimary"],
        "titleBar.inactiveBackground": p["bgBase"],
        "titleBar.inactiveForeground": p["textMuted"],
        "terminal.background": p["bgBase"],
        "terminal.foreground": p["textPrimary"],
        "focusBorder": p["accent"],
        "input.background": p["bgSurfaceHover"],
        "input.foreground": p["textPrimary"],
        "input.border": p["borderNormal"],
        "dropdown.background": p["bgSurfaceHover"],
        "dropdown.foreground": p["textPrimary"],
        "dropdown.border": p["borderNormal"],
        "list.activeSelectionBackground": p["bgSurfaceActive"],
        "list.activeSelectionForeground": p["textPrimary"],
        "list.hoverBackground": p["bgSurfaceHover"],
        # Right-click context menus in VSCodium
        "menu.background": p["bgSurface"],
        "menu.foreground": p["textPrimary"],
        "menu.selectionBackground": p["bgSurfaceHover"],
        "menu.selectionForeground": p["accent"],
        "menu.selectionBorder": p["accent"],
        "menu.border": p["borderNormal"],
        "menu.separatorBackground": p["borderDim"]
    }

    settings["workbench.colorCustomizations"] = customizations

    with open(settings_path, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=4)

    print(f"  ✓ VSCodium synced: {palette['name']}")

def find_zen_profiles():
    """Find all active Zen browser profile directories."""
    zen_dirs = [HOME / ".config" / "zen", HOME / ".zen"]
    profiles = set()
    for zd in zen_dirs:
        if not zd.exists():
            continue
        # Scan for existing prefs.js
        for prefs in zd.glob("*/prefs.js"):
            profiles.add(prefs.parent)
        # Also parse profiles.ini to discover all configured profiles
        ini_file = zd / "profiles.ini"
        if ini_file.exists():
            import configparser
            cfg = configparser.ConfigParser()
            try:
                cfg.read(ini_file)
                for section in cfg.sections():
                    if section.startswith("Profile") or section.startswith("Install"):
                        p_path = cfg.get(section, "Path", fallback=None) or cfg.get(section, "Default", fallback=None)
                        if p_path:
                            target = (zd / p_path).resolve()
                            if target.exists() and target.is_dir():
                                profiles.add(target)
            except Exception:
                pass
    return list(profiles)

def sync_zen(palette):
    """
    Sync Zen Browser using Noctalia's official userChrome & userContent architecture.
    Applies colors to native CSS variables, eliminates double borders, and preserves floating sidebar.
    """
    p = palette
    zen_theme_dir = CONFIG_DIR / "theme" / "zen"
    chrome_template_file = zen_theme_dir / "zen-userChrome.css"
    content_template_file = zen_theme_dir / "zen-userContent.css"

    if not chrome_template_file.exists() or not content_template_file.exists():
        print(f"  ! Warning: Zen templates not found in {zen_theme_dir}")
        return

    with open(chrome_template_file, "r", encoding="utf-8") as f:
        chrome_tmpl = f.read()

    with open(content_template_file, "r", encoding="utf-8") as f:
        content_tmpl = f.read()

    replacements = {
        "{{colors.background.dark.hex}}": p["bgBase"],
        "{{colors.surface_container_low.dark.hex}}": p["bgSurface"],
        "{{colors.surface_container.dark.hex}}": p["bgSurfaceHover"],
        "{{colors.surface_container_high.dark.hex}}": p["bgSurfaceHover"],
        "{{colors.surface_container_highest.dark.hex}}": p["bgSurfaceActive"],
        "{{colors.surface_bright.dark.hex}}": p["borderBright"],
        "{{colors.outline_variant.dark.hex}}": p["borderNormal"],
        "{{colors.outline.dark.hex}}": p["borderDim"],
        "{{colors.on_surface_variant.dark.hex}}": p["textSecondary"],
        "{{colors.on_surface.dark.hex}}": p["textPrimary"],
        "{{colors.primary.dark.hex}}": p["accent"],
        "{{colors.secondary.dark.hex}}": p.get("blue", p["accent"]),
        "{{colors.tertiary.dark.hex}}": p.get("purple", p["accent"]),
        "{{colors.error.dark.hex}}": p.get("red", "#f7768e"),

        "{{colors.background.light.hex}}": p["bgBase"],
        "{{colors.surface_container_low.light.hex}}": p["bgSurface"],
        "{{colors.surface_container.light.hex}}": p["bgSurfaceHover"],
        "{{colors.surface_container_high.light.hex}}": p["bgSurfaceHover"],
        "{{colors.surface_container_highest.light.hex}}": p["bgSurfaceActive"],
        "{{colors.surface_bright.light.hex}}": p["borderBright"],
        "{{colors.outline_variant.light.hex}}": p["borderNormal"],
        "{{colors.outline.light.hex}}": p["borderDim"],
        "{{colors.on_surface_variant.light.hex}}": p["textSecondary"],
        "{{colors.on_surface.light.hex}}": p["textPrimary"],
        "{{colors.primary.light.hex}}": p["accent"],
        "{{colors.secondary.light.hex}}": p.get("blue", p["accent"]),
        "{{colors.tertiary.light.hex}}": p.get("purple", p["accent"]),
        "{{colors.error.light.hex}}": p.get("red", "#f7768e"),
    }

    compiled_chrome = chrome_tmpl
    compiled_content = content_tmpl
    for k, v in replacements.items():
        compiled_chrome = compiled_chrome.replace(k, v)
        compiled_content = compiled_content.replace(k, v)

    # 1. Write to cache directory (Noctalia standard location)
    cache_dir = HOME / ".cache" / "quickshell" / "zen-browser"
    cache_dir.mkdir(parents=True, exist_ok=True)
    with open(cache_dir / "zen-userChrome.css", "w", encoding="utf-8") as f:
        f.write(compiled_chrome)
    with open(cache_dir / "zen-userContent.css", "w", encoding="utf-8") as f:
        f.write(compiled_content)

    # 2. Write to each Zen profile
    profiles = find_zen_profiles()
    for prof in profiles:
        chrome_dir = prof / "chrome"
        chrome_dir.mkdir(parents=True, exist_ok=True)

        # Write direct profile copy
        prof_chrome_theme = chrome_dir / "quickshell-zen-theme.css"
        prof_content_theme = chrome_dir / "quickshell-zen-content.css"
        with open(prof_chrome_theme, "w", encoding="utf-8") as f:
            f.write(compiled_chrome)
        with open(prof_content_theme, "w", encoding="utf-8") as f:
            f.write(compiled_content)

        # Remove stale duplicate zen-theme.css if present
        stale_theme = chrome_dir / "zen-theme.css"
        if stale_theme.exists():
            try:
                stale_theme.unlink()
            except Exception:
                pass

        # Update user.js
        user_js = prof / "user.js"
        js_prefs = [
            'user_pref("devtools.chrome.enabled", true);',
            'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);',
            'user_pref("widget.gtk.rounded-bottom-corners.enabled", false);',
            'user_pref("zen.theme.border-radius", 0);',
            'user_pref("zen.theme.content-element-separation", 0);',
        ]
        managed_pref_keys = [
            "devtools.chrome.enabled",
            "toolkit.legacyUserProfileCustomizations.stylesheets",
            "widget.gtk.rounded-bottom-corners.enabled",
            "zen.theme.border-radius",
            "zen.theme.content-element-separation",
        ]
        existing_js = user_js.read_text(encoding="utf-8") if user_js.exists() else ""
        js_lines = [line for line in existing_js.splitlines() if not any(p in line for p in managed_pref_keys)]
        js_lines.extend(js_prefs)
        with open(user_js, "w", encoding="utf-8") as f:
            f.write("\n".join(js_lines) + "\n")

        # Update userChrome.css with @import
        user_chrome = chrome_dir / "userChrome.css"
        import_line = '@import "quickshell-zen-theme.css";'
        existing_chrome = user_chrome.read_text(encoding="utf-8") if user_chrome.exists() else ""
        
        # Strip any old quickshell generated block or quickshell import
        cleaned_lines = []
        skip = False
        for line in existing_chrome.splitlines():
            if "/* Generated by Quickshell Theme Sync" in line:
                skip = True
                continue
            if skip:
                continue
            if 'quickshell-zen-theme.css' in line or 'noctalia/zen-browser' in line or 'zen-userChrome.css' in line:
                continue
            cleaned_lines.append(line)

        new_chrome_content = f"{import_line}\n" + "\n".join(cleaned_lines).strip()
        with open(user_chrome, "w", encoding="utf-8") as f:
            f.write(new_chrome_content.strip() + "\n")

        # Update userContent.css with @import
        user_content = chrome_dir / "userContent.css"
        import_content_line = '@import "quickshell-zen-content.css";'
        existing_content = user_content.read_text(encoding="utf-8") if user_content.exists() else ""
        content_lines = [l for l in existing_content.splitlines() if 'quickshell-zen-content.css' not in l and 'noctalia/zen-browser' not in l and 'zen-userContent.css' not in l]
        new_content_body = f"{import_content_line}\n" + "\n".join(content_lines).strip()
        with open(user_content, "w", encoding="utf-8") as f:
            f.write(new_content_body.strip() + "\n")

    # Check if Zen is running
    is_running = False
    try:
        res = subprocess.run(["pgrep", "-f", "zen-bin"], capture_output=True, text=True)
        is_running = bool(res.stdout.strip())
    except Exception:
        pass

    status_note = " (restart Zen to apply changes)" if is_running else ""
    print(f"  ✓ Zen Browser synced: {palette['name']}{status_note}")

def main():
    if len(sys.argv) < 2:
        # Default to reading active_theme.txt
        active_file = CONFIG_DIR / "theme" / "active_theme.txt"
        if active_file.exists():
            theme_id = active_file.read_text().strip()
        else:
            theme_id = "tokyo-night"
    else:
        theme_id = sys.argv[1].strip()

    palettes = load_palettes()
    if theme_id not in palettes:
        print(f"Error: Unknown theme '{theme_id}'. Available: {list(palettes.keys())}")
        sys.exit(1)

    palette = palettes[theme_id]
    print(f"Syncing application themes to '{palette['name']}' ({theme_id})...")

    # 1. Safely and atomically persist active theme
    active_file = CONFIG_DIR / "theme" / "active_theme.txt"
    active_file.parent.mkdir(parents=True, exist_ok=True)
    tmp_file = active_file.with_suffix(".tmp")
    tmp_file.write_text(f"{theme_id}\n", encoding="utf-8")
    tmp_file.replace(active_file)

    # 2. Broadcast theme change to all running Quickshell instances in parallel
    configs = ["bar", "lock", "launcher", "osd", "clipboard", "wallpaper", "themes", "screenshot"]
    for cfg in configs:
        subprocess.Popen(
            ["quickshell", "ipc", "-p", str(CONFIG_DIR / f"{cfg}.qml"), "call", "theme", "setTheme", theme_id],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL
        )
    subprocess.Popen(
        ["quickshell", "ipc", "-p", str(CONFIG_DIR / "wallpaper.qml"), "call", "wallpaper", "themeChanged", theme_id],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )

    # 3. Synchronize external desktop applications
    sync_gtk(palette)
    sync_icons(palette)
    sync_ghostty(palette)
    sync_vscodium(palette)
    sync_zen(palette)

    print(f"Universal theme synchronization complete for '{palette['name']}'.")

if __name__ == "__main__":
    main()
