#!/usr/bin/env python3
"""
Universal Application Theme Synchronizer for Quickshell
Synchronizes active theme palette to:
1. GTK4 / Libadwaita (Nautilus, Loupe, GNOME Music, GNOME Camera, GNOME Calculator)
2. Ghostty terminal emulator
3. VSCodium
4. Zen Browser
"""

import sys
import os
import json
import glob
from pathlib import Path

HOME = Path.home()
CONFIG_DIR = HOME / ".config" / "quickshell"
PALETTES_FILE = CONFIG_DIR / "theme" / "palettes.json"

def load_palettes():
    if not PALETTES_FILE.exists():
        print(f"Error: Palettes file {PALETTES_FILE} does not exist.")
        sys.exit(1)
    with open(PALETTES_FILE, "r") as f:
        return json.load(f)

def sync_gtk(palette):
    """
    Sync GTK4 / Libadwaita and GTK3 themes.
    Applies to Nautilus, Loupe, GNOME Music, Camera, Calculator, etc.
    """
    gtk4_dir = HOME / ".config" / "gtk-4.0"
    gtk3_dir = HOME / ".config" / "gtk-3.0"
    gtk4_dir.mkdir(parents=True, exist_ok=True)
    gtk3_dir.mkdir(parents=True, exist_ok=True)

    # 1. Generate theme.css with full Libadwaita color definitions
    theme_css = f"""/* Generated by Quickshell Theme Sync - Palette: {palette['name']} */
@define-color accent_color {palette['accent']};
@define-color accent_bg_color {palette['accent']};
@define-color accent_fg_color {palette['bgBase']};

@define-color destructive_color {palette['red']};
@define-color destructive_bg_color {palette['red']};
@define-color destructive_fg_color #ffffff;

@define-color success_color {palette['green']};
@define-color success_bg_color {palette['green']};
@define-color success_fg_color #ffffff;

@define-color warning_color {palette['yellow']};
@define-color warning_bg_color {palette['yellow']};
@define-color warning_fg_color #ffffff;

@define-color error_color {palette['red']};
@define-color error_bg_color {palette['red']};
@define-color error_fg_color #ffffff;

@define-color window_bg_color {palette['bgBase']};
@define-color window_fg_color {palette['textPrimary']};

@define-color view_bg_color {palette['bgSurface']};
@define-color view_fg_color {palette['textPrimary']};

@define-color headerbar_bg_color {palette['bgBase']};
@define-color headerbar_fg_color {palette['textPrimary']};
@define-color headerbar_border_color {palette['borderNormal']};
@define-color headerbar_backdrop_color {palette['bgBase']};

@define-color card_bg_color {palette['bgSurface']};
@define-color card_fg_color {palette['textPrimary']};
@define-color card_border_color {palette['borderDim']};

@define-color popover_bg_color {palette['bgSurfaceHover']};
@define-color popover_fg_color {palette['textPrimary']};

@define-color dialog_bg_color {palette['bgBase']};
@define-color dialog_fg_color {palette['textPrimary']};

@define-color sidebar_bg_color {palette['bgBase']};
@define-color sidebar_fg_color {palette['textPrimary']};
@define-color sidebar_backdrop_color {palette['bgBase']};

@define-color secondary_sidebar_bg_color {palette['bgSurface']};
@define-color secondary_sidebar_fg_color {palette['textPrimary']};
@define-color secondary_sidebar_backdrop_color {palette['bgSurface']};
"""
    theme_file_4 = gtk4_dir / "theme.css"
    with open(theme_file_4, "w") as f:
        f.write(theme_css)

    # 2. Ensure gtk.css and gtk-dark.css in gtk-4.0 import theme.css
    # If they are currently symlinks to /usr/share/..., replace with real file
    base_import_content = """@import url('libadwaita.css');
@import url('libadwaita-tweaks.css');
@import url('theme.css');
"""
    for fname in ["gtk.css", "gtk-dark.css"]:
        fpath = gtk4_dir / fname
        if fpath.is_symlink():
            fpath.unlink()
            with open(fpath, "w") as f:
                f.write(base_import_content)
        elif fpath.exists():
            content = fpath.read_text()
            if "@import url('theme.css');" not in content:
                with open(fpath, "a") as f:
                    f.write("\n@import url('theme.css');\n")
            else:
                # Touch to trigger inotify in GTK applications
                fpath.touch()
        else:
            with open(fpath, "w") as f:
                f.write(base_import_content)

    # 3. Also configure gtk-3.0
    gtk3_theme = gtk3_dir / "gtk.css"
    if not gtk3_theme.exists():
        with open(gtk3_theme, "w") as f:
            f.write("@import url('../gtk-4.0/theme.css');\n")
    else:
        content = gtk3_theme.read_text()
        if "theme.css" not in content:
            with open(gtk3_theme, "a") as f:
                f.write("\n@import url('../gtk-4.0/theme.css');\n")
        else:
            gtk3_theme.touch()

    print(f"  ✓ GTK4 / Libadwaita & GTK3 synced: {palette['name']}")

def sync_ghostty(palette):
    """
    Sync Ghostty terminal emulator.
    Writes theme.ghostty and links it in config.ghostty.
    """
    ghostty_dir = HOME / ".config" / "ghostty"
    ghostty_dir.mkdir(parents=True, exist_ok=True)
    theme_ghostty = ghostty_dir / "theme.ghostty"
    config_ghostty = ghostty_dir / "config.ghostty"

    content = f"""# Ghostty Theme - Palette: {palette['name']}
# Generated by Quickshell Theme Sync - do not edit directly
background = {palette['bgBase']}
foreground = {palette['textPrimary']}
cursor-color = {palette['accent']}
cursor-text = {palette['bgBase']}
selection-background = {palette['bgSurfaceActive']}
selection-foreground = {palette['textPrimary']}

# 16-color ANSI Palette
palette = 0={palette['bgSurface']}
palette = 1={palette['red']}
palette = 2={palette['green']}
palette = 3={palette['yellow']}
palette = 4={palette['blue']}
palette = 5={palette['purple']}
palette = 6={palette['cyan']}
palette = 7={palette['textSecondary']}

palette = 8={palette['borderBright']}
palette = 9={palette['red']}
palette = 10={palette['green']}
palette = 11={palette['yellow']}
palette = 12={palette['accent']}
palette = 13={palette['magenta']}
palette = 14={palette['cyan']}
palette = 15={palette['textPrimary']}
"""
    with open(theme_ghostty, "w") as f:
        f.write(content)

    # Ensure config.ghostty includes ?theme.ghostty
    if not config_ghostty.exists():
        with open(config_ghostty, "w") as f:
            f.write("config-file = ?theme.ghostty\n")
    else:
        cfg_text = config_ghostty.read_text()
        if "theme.ghostty" not in cfg_text:
            with open(config_ghostty, "w") as f:
                f.write("config-file = ?theme.ghostty\n" + cfg_text)
        else:
            # Touch config to prompt Ghostty to reload
            config_ghostty.touch()

    print(f"  ✓ Ghostty synced: {palette['name']}")

def sync_vscodium(palette):
    """
    Sync VSCodium workbench and editor colors.
    Updates workbench.colorCustomizations in settings.json.
    """
    settings_path = HOME / ".config" / "VSCodium" / "User" / "settings.json"
    if not settings_path.parent.exists():
        settings_path.parent.mkdir(parents=True, exist_ok=True)

    settings = {}
    if settings_path.exists():
        try:
            with open(settings_path, "r", encoding="utf-8") as f:
                settings = json.load(f)
        except Exception as e:
            print(f"  ! Warning: could not parse VSCodium settings.json: {e}")
            settings = {}

    p = palette
    customizations = {
        "activityBar.background": p["bgBase"],
        "activityBar.foreground": p["accent"],
        "activityBar.activeBorder": p["accent"],
        "activityBarBadge.background": p["accent"],
        "activityBarBadge.foreground": p["bgBase"],
        "editor.background": p["bgBase"],
        "editor.foreground": p["textPrimary"],
        "editorLineNumber.foreground": p["borderBright"],
        "editorLineNumber.activeForeground": p["accent"],
        "editorCursor.foreground": p["accent"],
        "editor.selectionBackground": p["bgSurfaceActive"],
        "editorGroupHeader.tabsBackground": p["bgSurface"],
        "tab.activeBackground": p["bgBase"],
        "tab.activeForeground": p["textPrimary"],
        "tab.activeBorderTop": p["accent"],
        "tab.inactiveBackground": p["bgSurface"],
        "tab.inactiveForeground": p["textMuted"],
        "sideBar.background": p["bgSurface"],
        "sideBar.foreground": p["textPrimary"],
        "sideBarTitle.foreground": p["textSecondary"],
        "sideBarSectionHeader.background": p["bgSurfaceHover"],
        "sideBarSectionHeader.foreground": p["accent"],
        "statusBar.background": p["bgSurface"],
        "statusBar.foreground": p["textSecondary"],
        "statusBarItem.remoteBackground": p["accent"],
        "titleBar.activeBackground": p["bgBase"],
        "titleBar.activeForeground": p["textPrimary"],
        "titleBar.inactiveBackground": p["bgBase"],
        "titleBar.inactiveForeground": p["textMuted"],
        "terminal.background": p["bgBase"],
        "terminal.foreground": p["textPrimary"],
        "focusBorder": p["accent"],
        "input.background": p["bgSurfaceHover"],
        "input.foreground": p["textPrimary"],
        "input.border": p["borderNormal"],
        "dropdown.background": p["bgSurfaceHover"],
        "dropdown.foreground": p["textPrimary"],
        "dropdown.border": p["borderNormal"],
        "list.activeSelectionBackground": p["bgSurfaceActive"],
        "list.activeSelectionForeground": p["textPrimary"],
        "list.hoverBackground": p["bgSurfaceHover"]
    }

    settings["workbench.colorCustomizations"] = customizations

    with open(settings_path, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=4)

    print(f"  ✓ VSCodium synced: {palette['name']}")

def sync_zen(palette):
    """
    Sync Zen Browser colors via userChrome.css and zen-theme.css.
    """
    zen_dir = HOME / ".config" / "zen"
    if not zen_dir.exists():
        return

    # Locate default profile directory
    profiles = list(zen_dir.glob("*.Default*"))
    if not profiles:
        profiles = list(zen_dir.glob("*release*"))
    if not profiles:
        return

    for profile in profiles:
        chrome_dir = profile / "chrome"
        chrome_dir.mkdir(parents=True, exist_ok=True)
        zen_theme_file = chrome_dir / "zen-theme.css"
        user_chrome_file = chrome_dir / "userChrome.css"
        user_js_file = profile / "user.js"

        p = palette
        theme_css = f"""/* Generated by Quickshell Theme Sync - Palette: {p['name']} */
:root {{
  --zen-primary-color: {p['accent']} !important;
  --zen-colors-primary: {p['accent']} !important;
  --zen-colors-bg: {p['bgBase']} !important;
  --zen-colors-surface: {p['bgSurface']} !important;
  --zen-colors-surface-hover: {p['bgSurfaceHover']} !important;
  --zen-colors-border: {p['borderNormal']} !important;
  --zen-dialog-background: {p['bgBase']} !important;
  --toolbar-bgcolor: {p['bgBase']} !important;
  --toolbar-color: {p['textPrimary']} !important;
  --tab-selected-bgcolor: {p['bgSurface']} !important;
  --tab-selected-textcolor: {p['textPrimary']} !important;
  --tab-hover-bgcolor: {p['bgSurfaceHover']} !important;
  --newtab-background-color: {p['bgBase']} !important;
}}
"""
        with open(zen_theme_file, "w") as f:
            f.write(theme_css)

        # Ensure userChrome.css imports zen-theme.css
        if not user_chrome_file.exists():
            with open(user_chrome_file, "w") as f:
                f.write('@import url("zen-theme.css");\n')
        else:
            uc_text = user_chrome_file.read_text()
            if 'zen-theme.css' not in uc_text:
                with open(user_chrome_file, "w") as f:
                    f.write('@import url("zen-theme.css");\n' + uc_text)
            else:
                user_chrome_file.touch()

        # Ensure user.js has stylesheet preference enabled
        pref_line = 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);\n'
        if not user_js_file.exists():
            with open(user_js_file, "w") as f:
                f.write(pref_line)
        else:
            ujs_text = user_js_file.read_text()
            if "toolkit.legacyUserProfileCustomizations.stylesheets" not in ujs_text:
                with open(user_js_file, "a") as f:
                    f.write(pref_line)

    print(f"  ✓ Zen Browser synced: {palette['name']}")

def main():
    if len(sys.argv) < 2:
        # Default to reading active_theme.txt
        active_file = CONFIG_DIR / "theme" / "active_theme.txt"
        if active_file.exists():
            theme_id = active_file.read_text().strip()
        else:
            theme_id = "tokyo-night"
    else:
        theme_id = sys.argv[1].strip()

    palettes = load_palettes()
    if theme_id not in palettes:
        print(f"Error: Unknown theme '{theme_id}'. Available: {list(palettes.keys())}")
        sys.exit(1)

    palette = palettes[theme_id]
    print(f"Syncing application themes to '{palette['name']}' ({theme_id})...")

    sync_gtk(palette)
    sync_ghostty(palette)
    sync_vscodium(palette)
    sync_zen(palette)

    print(f"Universal theme synchronization complete for '{palette['name']}'.")

if __name__ == "__main__":
    main()
