#!/usr/bin/env python3
"""
Universal Application Theme Synchronizer for Quickshell
Synchronizes active theme palette to:
1. GTK4 / Libadwaita (Nautilus, Loupe, GNOME Music, GNOME Camera, GNOME Calculator)
2. Ghostty terminal emulator
3. VSCodium
4. Zen Browser
"""

import sys
import os
import json
import glob
import subprocess
from pathlib import Path

HOME = Path.home()
CONFIG_DIR = HOME / ".config" / "quickshell"
PALETTES_FILE = CONFIG_DIR / "theme" / "palettes.json"

def load_palettes():
    if not PALETTES_FILE.exists():
        print(f"Error: Palettes file {PALETTES_FILE} does not exist.")
        sys.exit(1)
    with open(PALETTES_FILE, "r") as f:
        return json.load(f)

def sync_gtk(palette):
    """
    Sync GTK4 / Libadwaita and GTK3 themes.
    Applies to Nautilus, Loupe, GNOME Music, Camera, Calculator, etc.
    """
    gtk4_dir = HOME / ".config" / "gtk-4.0"
    gtk3_dir = HOME / ".config" / "gtk-3.0"
    gtk4_dir.mkdir(parents=True, exist_ok=True)
    gtk3_dir.mkdir(parents=True, exist_ok=True)

    p = palette

    # 1. Generate theme.css with full Libadwaita color definitions, media query overrides, and element rules
    theme_css = f"""/* Generated by Quickshell Theme Sync - Palette: {p['name']} */

/* Dark mode media query override for Libadwaita */
@media (prefers-color-scheme: dark) {{
  @define-color accent_color {p['accent']};
  @define-color accent_bg_color {p['accent']};
  @define-color accent_fg_color {p['bgBase']};

  @define-color destructive_color {p['red']};
  @define-color destructive_bg_color {p['red']};
  @define-color destructive_fg_color #ffffff;

  @define-color success_color {p['green']};
  @define-color success_bg_color {p['green']};
  @define-color success_fg_color #ffffff;

  @define-color warning_color {p['yellow']};
  @define-color warning_bg_color {p['yellow']};
  @define-color warning_fg_color #ffffff;

  @define-color error_color {p['red']};
  @define-color error_bg_color {p['red']};
  @define-color error_fg_color #ffffff;

  @define-color window_bg_color {p['bgBase']};
  @define-color window_fg_color {p['textPrimary']};

  @define-color view_bg_color {p['bgSurface']};
  @define-color view_fg_color {p['textPrimary']};

  @define-color headerbar_bg_color {p['bgBase']};
  @define-color headerbar_fg_color {p['textPrimary']};
  @define-color headerbar_border_color {p['borderNormal']};
  @define-color headerbar_backdrop_color {p['bgBase']};

  @define-color card_bg_color {p['bgSurface']};
  @define-color card_fg_color {p['textPrimary']};
  @define-color card_border_color {p['borderDim']};

  @define-color popover_bg_color {p['bgSurfaceHover']};
  @define-color popover_fg_color {p['textPrimary']};

  @define-color dialog_bg_color {p['bgBase']};
  @define-color dialog_fg_color {p['textPrimary']};

  @define-color sidebar_bg_color {p['bgBase']};
  @define-color sidebar_fg_color {p['textPrimary']};
  @define-color sidebar_backdrop_color {p['bgBase']};

  @define-color secondary_sidebar_bg_color {p['bgSurface']};
  @define-color secondary_sidebar_fg_color {p['textPrimary']};
  @define-color secondary_sidebar_backdrop_color {p['bgSurface']};

  :root {{
    --accent-bg-color: {p['accent']};
    --accent-fg-color: {p['bgBase']};
    --accent-color: {p['accent']};
    --window-bg-color: {p['bgBase']};
    --window-fg-color: {p['textPrimary']};
    --view-bg-color: {p['bgSurface']};
    --view-fg-color: {p['textPrimary']};
    --headerbar-bg-color: {p['bgBase']};
    --headerbar-fg-color: {p['textPrimary']};
    --headerbar-border-color: {p['borderNormal']};
    --sidebar-bg-color: {p['bgBase']};
    --sidebar-fg-color: {p['textPrimary']};
    --card-bg-color: {p['bgSurface']};
    --card-fg-color: {p['textPrimary']};
    --dialog-bg-color: {p['bgBase']};
    --dialog-fg-color: {p['textPrimary']};
    --popover-bg-color: {p['bgSurfaceHover']};
    --popover-fg-color: {p['textPrimary']};
  }}
}}

/* Global definitions */
@define-color accent_color {p['accent']};
@define-color accent_bg_color {p['accent']};
@define-color accent_fg_color {p['bgBase']};
@define-color window_bg_color {p['bgBase']};
@define-color window_fg_color {p['textPrimary']};
@define-color view_bg_color {p['bgSurface']};
@define-color view_fg_color {p['textPrimary']};
@define-color headerbar_bg_color {p['bgBase']};
@define-color headerbar_fg_color {p['textPrimary']};
@define-color headerbar_border_color {p['borderNormal']};
@define-color card_bg_color {p['bgSurface']};
@define-color card_fg_color {p['textPrimary']};
@define-color sidebar_bg_color {p['bgBase']};
@define-color sidebar_fg_color {p['textPrimary']};

:root {{
  --accent-bg-color: {p['accent']};
  --accent-fg-color: {p['bgBase']};
  --accent-color: {p['accent']};
  --window-bg-color: {p['bgBase']};
  --window-fg-color: {p['textPrimary']};
  --view-bg-color: {p['bgSurface']};
  --view-fg-color: {p['textPrimary']};
  --headerbar-bg-color: {p['bgBase']};
  --headerbar-fg-color: {p['textPrimary']};
  --headerbar-border-color: {p['borderNormal']};
  --sidebar-bg-color: {p['bgBase']};
  --sidebar-fg-color: {p['textPrimary']};
  --card-bg-color: {p['bgSurface']};
  --card-fg-color: {p['textPrimary']};
}}

/* Window and background styling for Nautilus & all GTK4 apps (never match popups or popovers) */
window:not(popover):not(.popup),
window.background:not(popover):not(.popup),
.background:not(popover):not(.popup) {{
  background-color: {p['bgBase']};
  color: {p['textPrimary']};
}}

/* Popover & Context Menu styling: transparent outer surface with styled contents */
popover,
popover.background,
popover:backdrop,
window.popup,
window.popover {{
  background-color: transparent;
  background-image: none;
  box-shadow: none;
}}

popover > contents {{
  background-color: {p['bgSurfaceHover']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderNormal']};
  border-radius: 10px;
}}

popover modelbutton:hover,
popover modelbutton:selected,
popover row:hover,
popover row:selected {{
  background-color: {p['bgSurfaceActive']};
  color: {p['accent']};
}}

/* Headerbar global styling: seamless flat headers without cut-through lines */
headerbar,
headerbar.flat {{
  background-color: {p['bgBase']};
  color: {p['textPrimary']};
  border: none;
  box-shadow: none;
}}

/* 1. Left column: Sidebar and its header share bgBase */
.navigation-sidebar,
placessidebar,
placesview,
navigation-sidebar,
sidebar,
scrolledwindow.sidebar {{
  background-color: {p['bgBase']};
  color: {p['textPrimary']};
  border: none;
  box-shadow: none;
}}

/* 2. Single vertical divider between Sidebar and Content */
navigation-split-view > separator,
separator.sidebar,
.navigation-sidebar {{
  border-right: 1px solid {p['borderDim']};
}}

/* 3. Right column: Content view and top pathbar share unified bgSurface */
navigation-split-view > navigation-page:last-child,
navigation-split-view > navigation-page:last-child headerbar,
toolbarview > .top-bar,
toolbarview > .top-bar headerbar,
.view,
listview,
gridview,
columnview,
scrolledwindow.view,
.nautilus-list-view,
.nautilus-grid-view {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border-bottom: none;
  box-shadow: none;
}}

/* 4. Nautilus Path Bar buttons (e.g. [Trash], [Home]) */
.nautilus-path-button,
.nautilus-pathbar button {{
  background-color: {p['bgSurfaceHover']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderDim']};
  border-radius: 6px;
}}

.nautilus-path-button:hover,
.nautilus-pathbar button:hover {{
  background-color: {p['bgSurfaceActive']};
  color: {p['accent']};
  border-color: {p['borderNormal']};
}}

listview > row:selected,
gridview > child:selected,
columnview > row:selected,
.view:selected {{
  background-color: {p['bgSurfaceActive']};
  color: {p['accent']};
}}

button.suggested-action,
button.accent {{
  background-color: {p['accent']};
  color: {p['bgBase']};
}}

card {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderDim']};
}}
"""
    theme_file_4 = gtk4_dir / "theme.css"
    with open(theme_file_4, "w") as f:
        f.write(theme_css)

    # 2. Write theme_css directly into gtk.css and gtk-dark.css so inotify triggers on them
    for fname in ["gtk.css", "gtk-dark.css"]:
        fpath = gtk4_dir / fname
        if fpath.is_symlink():
            fpath.unlink()
        with open(fpath, "w") as f:
            f.write(theme_css)

    # 3. Also configure gtk-3.0
    gtk3_theme = gtk3_dir / "gtk.css"
    with open(gtk3_theme, "w") as f:
        f.write(theme_css)

    # Trigger GTK style cache flush in all running GTK apps by toggling gtk-theme to force D-Bus broadcast
    try:
        subprocess.run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "Adwaita"], capture_output=True)
        subprocess.run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "adw-gtk3-dark"], capture_output=True)
    except Exception:
        pass

    print(f"  ✓ GTK4 / Libadwaita & GTK3 synced: {p['name']}")

def sync_ghostty(palette):
    """
    Sync Ghostty terminal emulator.
    Writes theme.ghostty and links it in config.ghostty.
    """
    ghostty_dir = HOME / ".config" / "ghostty"
    ghostty_dir.mkdir(parents=True, exist_ok=True)
    theme_ghostty = ghostty_dir / "theme.ghostty"
    config_ghostty = ghostty_dir / "config.ghostty"

    content = f"""# Ghostty Theme - Palette: {palette['name']}
# Generated by Quickshell Theme Sync - do not edit directly
background = {palette['bgBase']}
foreground = {palette['textPrimary']}
cursor-color = {palette['accent']}
cursor-text = {palette['bgBase']}
selection-background = {palette['bgSurfaceActive']}
selection-foreground = {palette['textPrimary']}

# 16-color ANSI Palette
palette = 0={palette['bgSurface']}
palette = 1={palette['red']}
palette = 2={palette['green']}
palette = 3={palette['yellow']}
palette = 4={palette['blue']}
palette = 5={palette['purple']}
palette = 6={palette['cyan']}
palette = 7={palette['textSecondary']}

palette = 8={palette['borderBright']}
palette = 9={palette['red']}
palette = 10={palette['green']}
palette = 11={palette['yellow']}
palette = 12={palette['accent']}
palette = 13={palette['magenta']}
palette = 14={palette['cyan']}
palette = 15={palette['textPrimary']}
"""
    with open(theme_ghostty, "w") as f:
        f.write(content)

    # Ensure config.ghostty includes ?theme.ghostty
    if not config_ghostty.exists():
        with open(config_ghostty, "w") as f:
            f.write("config-file = ?theme.ghostty\n")
    else:
        cfg_text = config_ghostty.read_text()
        if "theme.ghostty" not in cfg_text:
            with open(config_ghostty, "w") as f:
                f.write("config-file = ?theme.ghostty\n" + cfg_text)
        else:
            config_ghostty.touch()

    # Signal Ghostty to reload configuration live (SIGUSR2)
    try:
        subprocess.run(["pkill", "-USR2", "-x", "ghostty"], capture_output=True)
    except Exception:
        pass

    print(f"  ✓ Ghostty synced: {palette['name']}")

def sync_vscodium(palette):
    """
    Sync VSCodium workbench and editor colors.
    Updates workbench.colorCustomizations in settings.json.
    """
    settings_path = HOME / ".config" / "VSCodium" / "User" / "settings.json"
    if not settings_path.parent.exists():
        settings_path.parent.mkdir(parents=True, exist_ok=True)

    settings = {}
    if settings_path.exists():
        try:
            with open(settings_path, "r", encoding="utf-8") as f:
                settings = json.load(f)
        except Exception as e:
            print(f"  ! Warning: could not parse VSCodium settings.json: {e}")
            settings = {}

    p = palette
    customizations = {
        "activityBar.background": p["bgBase"],
        "activityBar.foreground": p["accent"],
        "activityBar.activeBorder": p["accent"],
        "activityBarBadge.background": p["accent"],
        "activityBarBadge.foreground": p["bgBase"],
        "editor.background": p["bgBase"],
        "editor.foreground": p["textPrimary"],
        "editorLineNumber.foreground": p["borderBright"],
        "editorLineNumber.activeForeground": p["accent"],
        "editorCursor.foreground": p["accent"],
        "editor.selectionBackground": p["bgSurfaceActive"],
        "editorGroupHeader.tabsBackground": p["bgSurface"],
        "tab.activeBackground": p["bgBase"],
        "tab.activeForeground": p["textPrimary"],
        "tab.activeBorderTop": p["accent"],
        "tab.inactiveBackground": p["bgSurface"],
        "tab.inactiveForeground": p["textMuted"],
        "sideBar.background": p["bgSurface"],
        "sideBar.foreground": p["textPrimary"],
        "sideBarTitle.foreground": p["textSecondary"],
        "sideBarSectionHeader.background": p["bgSurfaceHover"],
        "sideBarSectionHeader.foreground": p["accent"],
        "statusBar.background": p["bgSurface"],
        "statusBar.foreground": p["textSecondary"],
        "statusBarItem.remoteBackground": p["accent"],
        "titleBar.activeBackground": p["bgBase"],
        "titleBar.activeForeground": p["textPrimary"],
        "titleBar.inactiveBackground": p["bgBase"],
        "titleBar.inactiveForeground": p["textMuted"],
        "terminal.background": p["bgBase"],
        "terminal.foreground": p["textPrimary"],
        "focusBorder": p["accent"],
        "input.background": p["bgSurfaceHover"],
        "input.foreground": p["textPrimary"],
        "input.border": p["borderNormal"],
        "dropdown.background": p["bgSurfaceHover"],
        "dropdown.foreground": p["textPrimary"],
        "dropdown.border": p["borderNormal"],
        "list.activeSelectionBackground": p["bgSurfaceActive"],
        "list.activeSelectionForeground": p["textPrimary"],
        "list.hoverBackground": p["bgSurfaceHover"]
    }

    settings["workbench.colorCustomizations"] = customizations

    with open(settings_path, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=4)

    print(f"  ✓ VSCodium synced: {palette['name']}")

def sync_zen(palette):
    """
    Sync Zen Browser colors via userChrome.css and zen-theme.css.
    """
    zen_dir = HOME / ".config" / "zen"
    if not zen_dir.exists():
        return

    # Locate default profile directory
    profiles = list(zen_dir.glob("*.Default*"))
    if not profiles:
        profiles = list(zen_dir.glob("*release*"))
    if not profiles:
        return

    for profile in profiles:
        chrome_dir = profile / "chrome"
        chrome_dir.mkdir(parents=True, exist_ok=True)
        zen_theme_file = chrome_dir / "zen-theme.css"
        user_chrome_file = chrome_dir / "userChrome.css"
        user_js_file = profile / "user.js"
        prefs_js_file = profile / "prefs.js"

        p = palette
        theme_css = f"""/* Generated by Quickshell Theme Sync - Palette: {p['name']} */
:root {{
  --zen-primary-color: {p['accent']} !important;
  --zen-colors-primary: {p['accent']} !important;
  --zen-colors-hover-bg: {p['bgSurfaceHover']} !important;
  --zen-dialog-background: {p['bgBase']} !important;

  /* Standard Firefox Chrome Colors */
  --toolbar-bgcolor: {p['bgBase']} !important;
  --toolbar-color: {p['textPrimary']} !important;
  --tab-selected-bgcolor: {p['bgSurface']} !important;
  --tab-selected-textcolor: {p['textPrimary']} !important;
  --tab-hover-bgcolor: {p['bgSurfaceHover']} !important;
  --newtab-background-color: {p['bgBase']} !important;
  --lwt-accent-color: {p['bgBase']} !important;
  --lwt-text-color: {p['textPrimary']} !important;
  --lwt-selected-tab-background-color: {p['bgSurface']} !important;
  --arrowpanel-background: {p['bgSurface']} !important;
  --arrowpanel-color: {p['textPrimary']} !important;
  --arrowpanel-border-color: {p['borderDim']} !important;
}}

/* Main Window, Toolbox & Sidebars */
#main-window,
#browser,
#navigator-toolbox,
#TabsToolbar,
#zen-tabbox-wrapper,
hbox.browserSidebarContainer,
#zen-sidebar-web-panel,
#sidebar-box,
#sidebar-header {{
  background-color: {p['bgBase']} !important;
  color: {p['textPrimary']} !important;
}}

/* URL bar & Navigation bar */
#nav-bar,
#PersonalToolbar {{
  background-color: {p['bgBase']} !important;
  color: {p['textPrimary']} !important;
}}

#urlbar,
#urlbar-background,
.urlbar-background {{
  background-color: {p['bgSurface']} !important;
  color: {p['textPrimary']} !important;
  border-color: {p['borderNormal']} !important;
}}

#urlbar-input {{
  color: {p['textPrimary']} !important;
}}

/* Tabs */
.tabbrowser-tab .tab-background {{
  background-color: transparent !important;
}}

.tabbrowser-tab[selected="true"] .tab-background,
.tabbrowser-tab[visuallyselected="true"] .tab-background {{
  background-color: {p['bgSurface']} !important;
}}

.tabbrowser-tab:hover:not([selected="true"]) .tab-background {{
  background-color: {p['bgSurfaceHover']} !important;
}}

.tab-text {{
  color: {p['textPrimary']} !important;
}}

/* Accents */
#zen-current-workspace-indicator {{
  background-color: {p['accent']} !important;
}}
"""
        with open(zen_theme_file, "w") as f:
            f.write(theme_css)

        with open(user_chrome_file, "w") as f:
            f.write(theme_css)

        # Ensure user.js has stylesheet preference enabled
        pref_line = 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);\n'
        if not user_js_file.exists():
            with open(user_js_file, "w") as f:
                f.write(pref_line)
        else:
            ujs_text = user_js_file.read_text()
            if "toolkit.legacyUserProfileCustomizations.stylesheets" not in ujs_text:
                with open(user_js_file, "a") as f:
                    f.write(pref_line)

        # Also append to prefs.js if not present so it takes effect immediately
        if prefs_js_file.exists():
            pjs_text = prefs_js_file.read_text()
            if "toolkit.legacyUserProfileCustomizations.stylesheets" not in pjs_text:
                with open(prefs_js_file, "a") as f:
                    f.write(pref_line)

    print(f"  ✓ Zen Browser synced: {palette['name']}")

def main():
    if len(sys.argv) < 2:
        # Default to reading active_theme.txt
        active_file = CONFIG_DIR / "theme" / "active_theme.txt"
        if active_file.exists():
            theme_id = active_file.read_text().strip()
        else:
            theme_id = "tokyo-night"
    else:
        theme_id = sys.argv[1].strip()

    palettes = load_palettes()
    if theme_id not in palettes:
        print(f"Error: Unknown theme '{theme_id}'. Available: {list(palettes.keys())}")
        sys.exit(1)

    palette = palettes[theme_id]
    print(f"Syncing application themes to '{palette['name']}' ({theme_id})...")

    sync_gtk(palette)
    sync_ghostty(palette)
    sync_vscodium(palette)
    sync_zen(palette)

    print(f"Universal theme synchronization complete for '{palette['name']}'.")

if __name__ == "__main__":
    main()

