#!/usr/bin/env python3
"""
Universal Application Theme Synchronizer for Quickshell
Synchronizes active theme palette to:
1. GTK4 / Libadwaita (Nautilus, Loupe, GNOME Music, GNOME Camera, GNOME Calculator)
2. Ghostty terminal emulator
3. VSCodium
4. Zen Browser
"""

import sys
import os
import json
import glob
import time
import subprocess
from pathlib import Path

HOME = Path.home()
CONFIG_DIR = HOME / ".config" / "quickshell"
PALETTES_FILE = CONFIG_DIR / "theme" / "palettes.json"

def load_palettes():
    if not PALETTES_FILE.exists():
        print(f"Error: Palettes file {PALETTES_FILE} does not exist.")
        sys.exit(1)
    with open(PALETTES_FILE, "r") as f:
        return json.load(f)

def sync_gtk(palette):
    """
    Sync GTK4 / Libadwaita and GTK3 themes.
    Applies to Nautilus, Loupe, GNOME Music, Camera, Calculator, etc.
    """
    gtk4_dir = HOME / ".config" / "gtk-4.0"
    gtk3_dir = HOME / ".config" / "gtk-3.0"
    gtk4_dir.mkdir(parents=True, exist_ok=True)
    gtk3_dir.mkdir(parents=True, exist_ok=True)

    p = palette

    # 1. Generate theme.css with full Libadwaita color definitions, media query overrides, and element rules
    theme_css = f"""/* Generated by Quickshell Theme Sync - Palette: {p['name']} */

/* Dark mode media query override for Libadwaita */
@media (prefers-color-scheme: dark) {{
  @define-color accent_color {p['accent']};
  @define-color accent_bg_color {p['accent']};
  @define-color accent_fg_color {p['bgBase']};

  @define-color destructive_color {p['red']};
  @define-color destructive_bg_color {p['red']};
  @define-color destructive_fg_color #ffffff;

  @define-color success_color {p['green']};
  @define-color success_bg_color {p['green']};
  @define-color success_fg_color #ffffff;

  @define-color warning_color {p['yellow']};
  @define-color warning_bg_color {p['yellow']};
  @define-color warning_fg_color #ffffff;

  @define-color error_color {p['red']};
  @define-color error_bg_color {p['red']};
  @define-color error_fg_color #ffffff;

  @define-color window_bg_color {p['bgBase']};
  @define-color window_fg_color {p['textPrimary']};

  @define-color view_bg_color {p['bgSurface']};
  @define-color view_fg_color {p['textPrimary']};

  @define-color headerbar_bg_color {p['bgBase']};
  @define-color headerbar_fg_color {p['textPrimary']};
  @define-color headerbar_border_color {p['borderNormal']};
  @define-color headerbar_backdrop_color {p['bgBase']};

  @define-color card_bg_color {p['bgSurface']};
  @define-color card_fg_color {p['textPrimary']};
  @define-color card_border_color {p['borderDim']};

  @define-color popover_bg_color {p['bgSurface']};
  @define-color popover_fg_color {p['textPrimary']};
  @define-color popover_border_color {p['borderNormal']};

  @define-color dialog_bg_color {p['bgBase']};
  @define-color dialog_fg_color {p['textPrimary']};

  @define-color sidebar_bg_color {p['bgBase']};
  @define-color sidebar_fg_color {p['textPrimary']};
  @define-color sidebar_backdrop_color {p['bgBase']};
  @define-color sidebar_border_color {p['borderDim']};

  @define-color secondary_sidebar_bg_color {p['bgSurface']};
  @define-color secondary_sidebar_fg_color {p['textPrimary']};
  @define-color secondary_sidebar_backdrop_color {p['bgSurface']};

  :root {{
    --accent-bg-color: {p['accent']};
    --accent-fg-color: {p['bgBase']};
    --accent-color: {p['accent']};
    --window-bg-color: {p['bgBase']};
    --window-fg-color: {p['textPrimary']};
    --view-bg-color: {p['bgSurface']};
    --view-fg-color: {p['textPrimary']};
    --headerbar-bg-color: {p['bgBase']};
    --headerbar-fg-color: {p['textPrimary']};
    --headerbar-border-color: {p['borderNormal']};
    --sidebar-bg-color: {p['bgBase']};
    --sidebar-fg-color: {p['textPrimary']};
    --sidebar-border-color: {p['borderDim']};
    --card-bg-color: {p['bgSurface']};
    --card-fg-color: {p['textPrimary']};
    --dialog-bg-color: {p['bgBase']};
    --dialog-fg-color: {p['textPrimary']};
    --popover-bg-color: {p['bgSurface']};
    --popover-fg-color: {p['textPrimary']};
    --popover-border-color: {p['borderNormal']};
  }}
}}

/* Global definitions */
@define-color accent_color {p['accent']};
@define-color accent_bg_color {p['accent']};
@define-color accent_fg_color {p['bgBase']};
@define-color window_bg_color {p['bgBase']};
@define-color window_fg_color {p['textPrimary']};
@define-color view_bg_color {p['bgSurface']};
@define-color view_fg_color {p['textPrimary']};
@define-color headerbar_bg_color {p['bgBase']};
@define-color headerbar_fg_color {p['textPrimary']};
@define-color headerbar_border_color {p['borderNormal']};
@define-color card_bg_color {p['bgSurface']};
@define-color card_fg_color {p['textPrimary']};
@define-color sidebar_bg_color {p['bgBase']};
@define-color sidebar_fg_color {p['textPrimary']};
@define-color sidebar_border_color {p['borderDim']};
@define-color popover_bg_color {p['bgSurface']};
@define-color popover_fg_color {p['textPrimary']};
@define-color popover_border_color {p['borderNormal']};

:root {{
  --accent-bg-color: {p['accent']};
  --accent-fg-color: {p['bgBase']};
  --accent-color: {p['accent']};
  --window-bg-color: {p['bgBase']};
  --window-fg-color: {p['textPrimary']};
  --view-bg-color: {p['bgSurface']};
  --view-fg-color: {p['textPrimary']};
  --headerbar-bg-color: {p['bgBase']};
  --headerbar-fg-color: {p['textPrimary']};
  --headerbar-border-color: {p['borderNormal']};
  --sidebar-bg-color: {p['bgBase']};
  --sidebar-fg-color: {p['textPrimary']};
  --sidebar-border-color: {p['borderDim']};
  --card-bg-color: {p['bgSurface']};
  --card-fg-color: {p['textPrimary']};
  --popover-bg-color: {p['bgSurface']};
  --popover-fg-color: {p['textPrimary']};
  --popover-border-color: {p['borderNormal']};
}}

/* Base Window styling (excluding popups / popovers) */
window:not(popover):not(.popup),
window.background:not(popover):not(.popup),
.background:not(popover):not(.popup) {{
  background-color: {p['bgBase']};
  color: {p['textPrimary']};
}}

/* Headerbar global styling */
headerbar,
headerbar.flat {{
  background-color: {p['bgBase']};
  color: {p['textPrimary']};
  border: none;
  box-shadow: none;
}}

/* ====================================================================
   Nautilus & Libadwaita Two-Column Split Architecture
   ==================================================================== */

/* Left column: Sidebar, its headerbar, and listbox share bgBase */
overlay-split-view > .sidebar-pane,
.sidebar-pane,
.sidebar-pane headerbar,
.sidebar-pane toolbarview,
.sidebar-pane listbox,
.sidebar-pane scrolledwindow,
.navigation-sidebar,
placessidebar,
placesview {{
  background-color: {p['bgBase']};
  color: {p['textPrimary']};
  border: none;
  box-shadow: none;
}}

/* Remove default Libadwaita inner shadow from sidebar pane */
overlay-split-view > .sidebar-pane:dir(ltr),
overlay-split-view > .sidebar-pane:dir(rtl),
.sidebar-pane:dir(ltr),
.sidebar-pane:dir(rtl) {{
  box-shadow: none;
}}

/* Single clean 1px vertical divider between Sidebar and Content */
overlay-split-view > border {{
  background-color: {p['borderDim']};
  min-width: 1px;
  min-height: 1px;
  border: none;
  box-shadow: none;
}}

overlay-split-view > shadow {{
  background-image: none;
  background: none;
  box-shadow: none;
}}

.sidebar-pane {{
  border-right: 1px solid {p['borderDim']};
}}

/* Sidebar row styling */
.sidebar-pane row,
.sidebar-pane listbox > row,
.navigation-sidebar listview > row,
placessidebar row {{
  background-color: transparent;
  color: {p['textPrimary']};
  border-radius: 6px;
  margin: 1px 4px;
}}

.sidebar-pane row:hover,
.sidebar-pane listbox > row:hover,
.navigation-sidebar listview > row:hover,
placessidebar row:hover {{
  background-color: {p['bgSurfaceHover']};
  color: {p['textPrimary']};
}}

.sidebar-pane row:selected,
.sidebar-pane listbox > row:selected,
.navigation-sidebar listview > row:selected,
placessidebar row:selected {{
  background-color: {p['bgSurfaceActive']};
  color: {p['accent']};
}}

.sidebar-pane row:selected label,
.sidebar-pane row:selected image,
.navigation-sidebar row:selected label {{
  color: {p['accent']};
}}

.sidebar-pane separator,
placessidebar separator {{
  background-color: {p['borderDim']};
  min-height: 1px;
  margin: 6px 12px;
}}

/* Right column: Content view, top location bar, and folder grid/list share unified bgSurface */
overlay-split-view > .content-pane,
.content-pane,
.content-pane toolbarview,
.content-pane .top-bar,
.content-pane headerbar,
.content-pane toolbarview > .top-bar,
.content-pane toolbarview > .top-bar headerbar {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: none;
  border-bottom: none;
  box-shadow: none;
}}

.content-pane scrolledwindow,
.content-pane .nautilus-files-view,
.content-pane .nautilus-list-view,
.content-pane .nautilus-grid-view,
.content-pane gridview,
.content-pane listview,
.content-pane columnview,
scrolledwindow.view {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: none;
}}

/* Nautilus Path Bar buttons (e.g. [Home], [Trash]) */
.nautilus-path-button,
.nautilus-pathbar button {{
  background-color: {p['bgSurfaceHover']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderDim']};
  border-radius: 6px;
}}

.nautilus-path-button:hover,
.nautilus-pathbar button:hover {{
  background-color: {p['bgSurfaceActive']};
  color: {p['accent']};
  border-color: {p['borderNormal']};
}}

/* Selected items in folder view */
.content-pane gridview > child:selected,
.content-pane listview > row:selected,
.content-pane columnview row:selected {{
  background-color: {p['bgSurfaceActive']};
  color: {p['accent']};
  border-radius: 6px;
}}

.content-pane gridview > child:hover,
.content-pane listview > row:hover {{
  background-color: {p['bgSurfaceHover']};
  border-radius: 6px;
}}

/* Action buttons */
button.suggested-action,
button.accent {{
  background-color: {p['accent']};
  color: {p['bgBase']};
}}

card {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderDim']};
}}

/* ====================================================================
   Popovers, Menus & Context Menus Across All 11 Theme Variants
   ==================================================================== */

popover,
popover.background,
popover:backdrop,
window.popup,
window.popover {{
  background-color: transparent;
  background-image: none;
  box-shadow: none;
  border: none;
}}

popover > contents,
popover.menu > contents,
.popover > contents {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderNormal']};
  border-radius: 10px;
  padding: 6px;
  box-shadow: 0 6px 20px rgba(0, 0, 0, 0.5);
}}

popover modelbutton,
popover.menu modelbutton,
popover button {{
  color: {p['textPrimary']};
  background-color: transparent;
  border-radius: 6px;
  min-height: 28px;
  padding: 2px 10px;
}}

popover modelbutton label,
popover.menu modelbutton label {{
  color: inherit;
}}

popover modelbutton:hover,
popover modelbutton:selected,
popover.menu modelbutton:hover,
popover.menu modelbutton:selected,
popover row:hover,
popover row:selected {{
  background-color: {p['bgSurfaceHover']};
  color: {p['accent']};
}}

popover modelbutton:hover label,
popover.menu modelbutton:hover label,
popover modelbutton:selected label,
popover.menu modelbutton:selected label {{
  color: {p['accent']};
}}

popover separator,
popover.menu separator {{
  background-color: {p['borderDim']};
  min-height: 1px;
  margin: 4px 6px;
}}

/* GTK3 Classic Menus */
menu,
.menu {{
  background-color: {p['bgSurface']};
  color: {p['textPrimary']};
  border: 1px solid {p['borderNormal']};
  border-radius: 8px;
  padding: 4px;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.4);
}}

menuitem,
.menu menuitem {{
  color: {p['textPrimary']};
  border-radius: 4px;
  padding: 4px 8px;
}}

menuitem:hover,
.menu menuitem:hover {{
  background-color: {p['bgSurfaceHover']};
  color: {p['accent']};
}}

menu separator,
separator.menuitem {{
  background-color: {p['borderDim']};
  min-height: 1px;
  margin: 4px 6px;
}}
"""
    theme_file_4 = gtk4_dir / "theme.css"
    with open(theme_file_4, "w") as f:
        f.write(theme_css)

    # 2. Write theme_css directly into gtk.css and gtk-dark.css so inotify triggers on them
    for fname in ["gtk.css", "gtk-dark.css"]:
        fpath = gtk4_dir / fname
        if fpath.is_symlink():
            fpath.unlink()
        with open(fpath, "w") as f:
            f.write(theme_css)

    # 3. Also configure gtk-3.0
    gtk3_theme = gtk3_dir / "gtk.css"
    with open(gtk3_theme, "w") as f:
        f.write(theme_css)

    # Trigger GTK style cache flush in all running GTK apps by toggling gtk-theme to force D-Bus broadcast
    try:
        subprocess.run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "Adwaita"], capture_output=True)
        subprocess.run(["gsettings", "set", "org.gnome.desktop.interface", "gtk-theme", "adw-gtk3-dark"], capture_output=True)
    except Exception:
        pass

    # If Nautilus is currently open, seamlessly restart it with the new theme
    try:
        check_nautilus = subprocess.run(["pgrep", "-x", "nautilus"], capture_output=True).returncode == 0
        if check_nautilus:
            subprocess.run(["nautilus", "-q"], capture_output=True)
            subprocess.run(["pkill", "-x", "nautilus"], capture_output=True)
            time.sleep(0.3)
            subprocess.Popen(["nautilus", "--no-desktop"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except Exception:
        pass

    print(f"  ✓ GTK4 / Libadwaita & GTK3 synced: {p['name']}")

def sync_ghostty(palette):
    """
    Sync Ghostty terminal emulator.
    Writes theme.ghostty and links it in config.ghostty and config.
    """
    ghostty_dir = HOME / ".config" / "ghostty"
    ghostty_dir.mkdir(parents=True, exist_ok=True)
    theme_ghostty = ghostty_dir / "theme.ghostty"

    content = f"""# Ghostty Theme - Palette: {palette['name']}
# Generated by Quickshell Theme Sync - do not edit directly
background = {palette['bgBase']}
foreground = {palette['textPrimary']}
cursor-color = {palette['accent']}
cursor-text = {palette['bgBase']}
selection-background = {palette['bgSurfaceActive']}
selection-foreground = {palette['textPrimary']}

# 16-color ANSI Palette
palette = 0={palette['bgSurface']}
palette = 1={palette['red']}
palette = 2={palette['green']}
palette = 3={palette['yellow']}
palette = 4={palette['blue']}
palette = 5={palette['purple']}
palette = 6={palette['cyan']}
palette = 7={palette['textSecondary']}

palette = 8={palette['borderBright']}
palette = 9={palette['red']}
palette = 10={palette['green']}
palette = 11={palette['yellow']}
palette = 12={palette['accent']}
palette = 13={palette['magenta']}
palette = 14={palette['cyan']}
palette = 15={palette['textPrimary']}
"""
    with open(theme_ghostty, "w") as f:
        f.write(content)

    # Ensure config.ghostty and config include ?theme.ghostty
    for cfg_name in ["config.ghostty", "config"]:
        cfg_file = ghostty_dir / cfg_name
        if not cfg_file.exists():
            with open(cfg_file, "w") as f:
                f.write("config-file = ?theme.ghostty\n")
        else:
            cfg_text = cfg_file.read_text()
            if "theme.ghostty" not in cfg_text:
                with open(cfg_file, "w") as f:
                    f.write("config-file = ?theme.ghostty\n" + cfg_text)
            else:
                cfg_file.touch()

    # Signal Ghostty to reload configuration live (SIGUSR2)
    try:
        subprocess.run(["pkill", "-SIGUSR2", "-x", "ghostty"], capture_output=True)
    except Exception:
        pass

    print(f"  ✓ Ghostty synced: {palette['name']}")

def sync_vscodium(palette):
    """
    Sync VSCodium workbench and editor colors.
    Updates workbench.colorCustomizations in settings.json.
    """
    settings_path = HOME / ".config" / "VSCodium" / "User" / "settings.json"
    if not settings_path.parent.exists():
        settings_path.parent.mkdir(parents=True, exist_ok=True)

    settings = {}
    if settings_path.exists():
        try:
            with open(settings_path, "r", encoding="utf-8") as f:
                settings = json.load(f)
        except Exception as e:
            print(f"  ! Warning: could not parse VSCodium settings.json: {e}")
            settings = {}

    p = palette
    customizations = {
        "activityBar.background": p["bgBase"],
        "activityBar.foreground": p["accent"],
        "activityBar.activeBorder": p["accent"],
        "activityBarBadge.background": p["accent"],
        "activityBarBadge.foreground": p["bgBase"],
        "editor.background": p["bgBase"],
        "editor.foreground": p["textPrimary"],
        "editorLineNumber.foreground": p["borderBright"],
        "editorLineNumber.activeForeground": p["accent"],
        "editorCursor.foreground": p["accent"],
        "editor.selectionBackground": p["bgSurfaceActive"],
        "editorGroupHeader.tabsBackground": p["bgSurface"],
        "tab.activeBackground": p["bgBase"],
        "tab.activeForeground": p["textPrimary"],
        "tab.activeBorderTop": p["accent"],
        "tab.inactiveBackground": p["bgSurface"],
        "tab.inactiveForeground": p["textMuted"],
        "sideBar.background": p["bgSurface"],
        "sideBar.foreground": p["textPrimary"],
        "sideBarTitle.foreground": p["textSecondary"],
        "sideBarSectionHeader.background": p["bgSurfaceHover"],
        "sideBarSectionHeader.foreground": p["accent"],
        "statusBar.background": p["bgSurface"],
        "statusBar.foreground": p["textSecondary"],
        "statusBarItem.remoteBackground": p["accent"],
        "titleBar.activeBackground": p["bgBase"],
        "titleBar.activeForeground": p["textPrimary"],
        "titleBar.inactiveBackground": p["bgBase"],
        "titleBar.inactiveForeground": p["textMuted"],
        "terminal.background": p["bgBase"],
        "terminal.foreground": p["textPrimary"],
        "focusBorder": p["accent"],
        "input.background": p["bgSurfaceHover"],
        "input.foreground": p["textPrimary"],
        "input.border": p["borderNormal"],
        "dropdown.background": p["bgSurfaceHover"],
        "dropdown.foreground": p["textPrimary"],
        "dropdown.border": p["borderNormal"],
        "list.activeSelectionBackground": p["bgSurfaceActive"],
        "list.activeSelectionForeground": p["textPrimary"],
        "list.hoverBackground": p["bgSurfaceHover"],
        # Right-click context menus in VSCodium
        "menu.background": p["bgSurface"],
        "menu.foreground": p["textPrimary"],
        "menu.selectionBackground": p["bgSurfaceHover"],
        "menu.selectionForeground": p["accent"],
        "menu.selectionBorder": p["accent"],
        "menu.border": p["borderNormal"],
        "menu.separatorBackground": p["borderDim"]
    }

    settings["workbench.colorCustomizations"] = customizations

    with open(settings_path, "w", encoding="utf-8") as f:
        json.dump(settings, f, indent=4)

    print(f"  ✓ VSCodium synced: {palette['name']}")

def sync_zen(palette):
    """
    Sync Zen Browser colors via userChrome.css and zen-theme.css.
    """
    zen_dir = HOME / ".config" / "zen"
    if not zen_dir.exists():
        return

    # Locate default profile directory
    profiles = list(zen_dir.glob("*.Default*"))
    if not profiles:
        profiles = list(zen_dir.glob("*release*"))
    if not profiles:
        return

    for profile in profiles:
        chrome_dir = profile / "chrome"
        chrome_dir.mkdir(parents=True, exist_ok=True)
        zen_theme_file = chrome_dir / "zen-theme.css"
        user_chrome_file = chrome_dir / "userChrome.css"
        user_js_file = profile / "user.js"
        prefs_js_file = profile / "prefs.js"

        p = palette
        theme_css = f"""/* Generated by Quickshell Theme Sync - Palette: {p['name']} */
:root {{
  --zen-primary-color: {p['accent']} !important;
  --zen-colors-primary: {p['accent']} !important;
  --zen-colors-hover-bg: {p['bgSurfaceHover']} !important;
  --zen-dialog-background: {p['bgBase']} !important;

  /* Standard Firefox Chrome Colors */
  --toolbar-bgcolor: {p['bgBase']} !important;
  --toolbar-color: {p['textPrimary']} !important;
  --tab-selected-bgcolor: {p['bgSurface']} !important;
  --tab-selected-textcolor: {p['textPrimary']} !important;
  --tab-hover-bgcolor: {p['bgSurfaceHover']} !important;
  --newtab-background-color: {p['bgBase']} !important;
  --lwt-accent-color: {p['bgBase']} !important;
  --lwt-text-color: {p['textPrimary']} !important;
  --lwt-selected-tab-background-color: {p['bgSurface']} !important;
  --arrowpanel-background: {p['bgSurface']} !important;
  --arrowpanel-color: {p['textPrimary']} !important;
  --arrowpanel-border-color: {p['borderDim']} !important;
}}

/* Main Window, Toolbox & Sidebars */
#main-window,
#browser,
#navigator-toolbox,
#TabsToolbar,
#zen-tabbox-wrapper,
hbox.browserSidebarContainer,
#zen-sidebar-web-panel,
#sidebar-box,
#sidebar-header {{
  background-color: {p['bgBase']} !important;
  color: {p['textPrimary']} !important;
}}

/* URL bar & Navigation bar */
#nav-bar,
#PersonalToolbar {{
  background-color: {p['bgBase']} !important;
  color: {p['textPrimary']} !important;
}}

#urlbar,
#urlbar-background,
.urlbar-background {{
  background-color: {p['bgSurface']} !important;
  color: {p['textPrimary']} !important;
  border-color: {p['borderNormal']} !important;
}}

#urlbar-input {{
  color: {p['textPrimary']} !important;
}}

/* Tabs */
.tabbrowser-tab .tab-background {{
  background-color: transparent !important;
}}

.tabbrowser-tab[selected="true"] .tab-background,
.tabbrowser-tab[visuallyselected="true"] .tab-background {{
  background-color: {p['bgSurface']} !important;
}}

.tabbrowser-tab:hover:not([selected="true"]) .tab-background {{
  background-color: {p['bgSurfaceHover']} !important;
}}

.tab-text {{
  color: {p['textPrimary']} !important;
}}

/* Accents */
#zen-current-workspace-indicator {{
  background-color: {p['accent']} !important;
}}

/* Context Menus / Popups in Zen / Firefox */
menupopup,
panel[type="autocomplete-richlistbox"] {{
  --panel-background: {p['bgSurface']} !important;
  --panel-color: {p['textPrimary']} !important;
  --panel-border-color: {p['borderNormal']} !important;
  --panel-shadow: 0 8px 24px rgba(0, 0, 0, 0.45) !important;
  background-color: {p['bgSurface']} !important;
  color: {p['textPrimary']} !important;
  border: 1px solid {p['borderNormal']} !important;
  border-radius: 8px !important;
  padding: 4px !important;
}}

menupopup menuitem,
menupopup menu {{
  color: {p['textPrimary']} !important;
  border-radius: 4px !important;
  padding: 4px 8px !important;
}}

menupopup menuitem:hover,
menupopup menu:hover,
menupopup menuitem[_moz-menuactive="true"],
menupopup menu[_moz-menuactive="true"] {{
  background-color: {p['bgSurfaceHover']} !important;
  color: {p['accent']} !important;
}}

menupopup menuseparator {{
  border-top: 1px solid {p['borderDim']} !important;
  margin: 4px 6px !important;
}}
"""
        with open(zen_theme_file, "w") as f:
            f.write(theme_css)

        with open(user_chrome_file, "w") as f:
            f.write(theme_css)

        # Ensure user.js has stylesheet preference enabled
        pref_line = 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);\n'
        if not user_js_file.exists():
            with open(user_js_file, "w") as f:
                f.write(pref_line)
        else:
            ujs_text = user_js_file.read_text()
            if "toolkit.legacyUserProfileCustomizations.stylesheets" not in ujs_text:
                with open(user_js_file, "a") as f:
                    f.write(pref_line)

        # Also append to prefs.js if not present so it takes effect immediately
        if prefs_js_file.exists():
            pjs_text = prefs_js_file.read_text()
            if "toolkit.legacyUserProfileCustomizations.stylesheets" not in pjs_text:
                with open(prefs_js_file, "a") as f:
                    f.write(pref_line)

    print(f"  ✓ Zen Browser synced: {palette['name']}")

def main():
    if len(sys.argv) < 2:
        # Default to reading active_theme.txt
        active_file = CONFIG_DIR / "theme" / "active_theme.txt"
        if active_file.exists():
            theme_id = active_file.read_text().strip()
        else:
            theme_id = "tokyo-night"
    else:
        theme_id = sys.argv[1].strip()

    palettes = load_palettes()
    if theme_id not in palettes:
        print(f"Error: Unknown theme '{theme_id}'. Available: {list(palettes.keys())}")
        sys.exit(1)

    palette = palettes[theme_id]
    print(f"Syncing application themes to '{palette['name']}' ({theme_id})...")

    sync_gtk(palette)
    sync_ghostty(palette)
    sync_vscodium(palette)
    sync_zen(palette)

    print(f"Universal theme synchronization complete for '{palette['name']}'.")

if __name__ == "__main__":
    main()
